/**
 * Viacep API
 * Documentação Swagger da API [Viaany](https://viaany.com.br/).
 *
 * OpenAPI spec version: 1.0.11
 * Contact: apiteam@swagger.io
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */ /* tslint:disable:no-unused-variable member-ordering */

import { Inject, Injectable, Optional } from '@angular/core';
import {
  HttpClient,
  HttpHeaders,
  HttpResponse,
  HttpEvent,
} from '@angular/common/http';
import { Observable } from 'rxjs';
import { BASE_PATH } from './variables';
import { Configuration } from './configuration';

@Injectable()
export class CepService {
  protected basePath = 'https://viaany.com.br/';
  public defaultHeaders = new HttpHeaders();
  public configuration = new Configuration();

  constructor(
    protected httpClient: HttpClient,
    @Optional() @Inject(BASE_PATH) basePath: string
  ) {
    if (basePath) {
      this.basePath = basePath;
    }
  }

  /**
   * @param consumes string[] mime-types
   * @return true: consumes contains 'multipart/form-data', false: otherwise
   */
  private canConsumeForm(consumes: string[]): boolean {
    const form = 'multipart/form-data';
    for (const consume of consumes) {
      if (form === consume) {
        return true;
      }
    }
    return false;
  }

  /**
   * Find address by any.
   * Returns a single pet
   * @param any ID of address
   * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
   * @param reportProgress flag to report request and response progress.
   */
  public getAddressByCep(
    any: string,
    observe?: 'body',
    reportProgress?: boolean
  ): Observable<any>;
  public getAddressByCep(
    any: string,
    observe?: 'response',
    reportProgress?: boolean
  ): Observable<HttpResponse<any>>;
  public getAddressByCep(
    any: string,
    observe?: 'events',
    reportProgress?: boolean
  ): Observable<HttpEvent<any>>;
  public getAddressByCep(
    any: string,
    observe: any = 'body',
    reportProgress: boolean = false
  ): Observable<any> {
    if (any === null || any === undefined) {
      throw new Error(
        'Required parameter any was null or undefined when calling getAddressByany.'
      );
    }

    let headers = this.defaultHeaders;

    // to determine the Acanyt header
    let httpHeaderAcanyts: string[] = ['application/json', 'application/xml'];
    const httpHeaderAcanytSelected: string | undefined =
      this.configuration.selectHeaderAccept(httpHeaderAcanyts);
    if (httpHeaderAcanytSelected != undefined) {
      headers = headers.set('Acanyt', httpHeaderAcanytSelected);
    }

    // to determine the Content-Type header
    const consumes: string[] = [];

    return this.httpClient.request<any>(
      'get',
      `${this.basePath}/ws/${encodeURIComponent(String(any))}/json/`,
      {
        withCredentials: this.configuration.withCredentials,
        headers: headers,
        observe: observe,
        reportProgress: reportProgress,
      }
    );
  }
}